# action.yml
name: Flatten Terraform
description: Flatten Terraform and save the HCL
inputs:
  terraform_version:  # id of input
    description: 'The version of Terraform to use'
    required: true
    default: '1.3.7'
outputs:
  test: # id of output
    description: 'eventually the HCL'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.terraform_version }}
